---
title: "Lab09"
author: "VY"
date: "`r Sys.Date()`"
output: 
  pdf_document: default
  html_document: default
  github_document: 
  html_preview: false
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Question 2

```{r}
set.seed(3000)
fun1 <- function(n = 100, k = 4, lambda = 4) {
  x <- NULL
  
  for (i in 1:n)
    x <- rbind(x, rpois(k, lambda))
  
  return(x)
}

f1 <-fun1(1000,4)
mean(f1)

fun1alt <- function(n = 100, k = 4, lambda = 4) {
  # YOUR CODE HERE
  x <- matrix( rpois(n*k, lambda) , ncol=4)
  
  return(x)
}
f1 <- fun1alt(50000,4)

# Benchmarking
microbenchmark::microbenchmark(
  fun1(),
  fun1alt()
)
```

# Function: Find column max
```{r}
# Data Generating Process (10 x 10,000 matrix)
set.seed(1234)
x <- matrix(rnorm(1e4), nrow=10)

# Find each column's max value
fun2 <- function(x) {
  apply(x, 2, max)
}


fun2alt <- function(x) {
  # YOUR CODE HERE
 idx <- max.col(t(x))
 x[cbind(idx,1:4)]
}


# Benchmarking
microbenchmark::microbenchmark(
  fun2(x),
  fun2alt(x)
)
```

# Bootstrapping

```{r}

```

